config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  resources :posts do
    resources :replies
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/reply.rb
class Reply < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/posts_controller.rb
require 'posts_helper'

class PostsController < ApplicationController
  include PostsHelper

  def index
    @posts = Post.all
    render :new
  end

  def new
    @post = Post.new
    render :new
  end

  def create
    @post = Post.new(post_params.permit(:title, :content))
    @post.user_id = current_user.id
    if @post.save
      # Here is a potential place to add Twilio API call to send text messages

      # If a file was uploaded, we expect its IO stream to be in params[:post][:image], and
      # will store it in Cloudinary
      if post_params[:image].present?
        auth = {
          cloud_name: Rails.application.secrets.cloudinary_cloud_name,
          api_key:    Rails.application.secrets.cloudinary_api_key,
          api_secret: Rails.application.secrets.cloudinary_api_secret
        }

        #cl_resp = Cloudinary::Uploader.upload(params[:post][:image], auth)
      end

      # Construct the API URL here, taking care to use Rails.application.secrets.bitly_api_key and
      # Rails.application.secrets.bitly_username, for the login, and Rails route helpers the post's url
      bitly_url = "http://api.bitly.com/..."

      # Once the URL is constructed, you can use the simple GET call below, via the Net::HTTP library, to pass the test.
      # Note that in general, when using Net::HTTP, you have to think about handling all of its possible exceptions. An
      # easier option might be to investigate the use of a Bitly gem, for example, https://github.com/philnash/bitly
      # which abstracts out errors for you in a more readable way.

      # resp = JSON.parse(Net::HTTP.get URI(bitly_url))

      redirect_to posts_url
    else
      render @post.errors.full_messages
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params.permit(:title, :content))
      flash[:success] = "Post updated"
      redirect_to @post
    else
      render 'edit'
    end
  end

  def show
    @post = Post.find(params[:id])
    render :index
  end

  def destroy
    @post = Post.find(params[:id])
    redirect_to new_posts_url
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :image)
  end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  def new
    @post = Post.find(params[:post_id])
    @reply = Reply.new
    render :index
  end

  def create
    @post = Post.find(params[:post_id])
    @reply = Reply.new(reply_params)
    @reply.user_id = current_user.id
    @reply.post_id = params[:post_id]
    if @reply.save
      redirect_to post_url(params[:post_id])
    else
      render @reply.errors.full_messages
    end
  end

  private

  def reply_params
    params.require(:reply).permit(:body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def find_user_email(id)
    @user = User.find(id)
    @user.email
  end

  def initiate_twilio_client
  end

  def sent_text_to_user(number)
  end

end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/home/index.html.erb
<p>Welcome to your home page!</p>
<br>
<img src="https://s-media-cache-ak0.pinimg.com/originals/59/70/a4/5970a4a6471a3803269b063ba57ebefb.gif" />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <div class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand">Message Board</a>
    </div>
    <ul class="nav navbar-nav">
      <li class=""><a href="/">Home</a></li>
      <li class=""><a href="/posts">Posts</a></li>
    </ul>
    <% if current_user %>
      <p class="navbar-text pull-right"> <%= current_user.email %> | <%= link_to "Log out", destroy_user_session_url, :method => :delete %> </p>
    <% end %>
  </div>
</div>
<div id="header">
  <div class="container">
    <div class="row">
      <%= yield %>
    </div>
  </div>
</div>

</body>
</html>

app/views/posts/edit.html.erb
<div id="header">
  <div class="container">
    <div class="row">
      <h1>Edit an existing post</h1>
      <br>
      <%= form_for @post do |form| %>
        <p>
          <%= form.label :title, "Title:" %>
          <%= form.text_field :title %>
        </p>
        <p>
          <%= form.label :content, "Content:" %>
          <%= form.text_field :content %>
        </p>
        <p class='buttons'>
          <%= form.submit "Edit event" %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div id="header">
  <div class="container">
    <div class="row">
      <h1> All posts </h1>
      <br>
      <table class="table">
        <% @posts.each do |post| %>
          <tr><a href="<%= post_url(post.id) %>"><%= post.title %></a></tr> by
          <tr><%= find_user_email(post.user_id) %></tr> at 
          <tr><%= post.created_at %></tr>
          <br>
        <% end %>
      </table>

    </div>
  </div>
  <br>
  <br>
  <%= button_to 'Create a new post', new_post_path, :method => :get %>
</div>

app/views/posts/new.html.erb
<div id="header">
  <div class="container">
    <div class="row">
      <h1>Add a new post</h1>
      <br>
      <%= form_for @post do |form| %>
        <p>
          <%= form.label :title, "Title:" %>
          <%= form.text_field :title %>
          <!-- make this field required -->
        </p>
        <p>
          <%= form.label :content, "Content:" %>
          <%= form.text_field :content %>
        </p>
        <p class='buttons'>
          <%= form.submit "Add post" %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div id="header">
  <div class="container">
    <div class="row">
      <h1> Post </h1>
      <br>
      Post title: <%= @post.title %>
      <br>
      <br>
      Post content: <%= @post.content %>
      <br>
      <br>
      Post replies:
      <br>
      <% @post.replies.each do |reply| %>
        <%= reply.body %> by
        <%= find_user_email(reply.user_id) %> at
        <%= reply.created_at %>
        <br>
      <% end %>
      <br>
      <%= button_to 'Edit', edit_post_path, :method => :get %>
      <br>
      <%= button_to 'Destroy', post_path, :confirm => 'Are you sure?', :method => :delete %>
      <br>
      <%= button_to 'Reply', new_post_reply_path(@post.id), :method => :get %>
    </div>
  </div>
</div>

app/views/replies/new.html.erb
<div id="header">
  <div class="container">
    <div class="row">
      <h1>Replying to <%= @post.title %></h1>
      <br>
      <%= form_for @reply, url: post_replies_path do |form| %>
        <p>
          <%= form.label :body, "Body:" %>
          <%= form.text_field :body %>
          <!-- make this field required -->
        </p>
        <p class='buttons'>
          <%= form.submit "Add reply" %>
        </p>
      <% end %>
    </div>
  </div>
</div>